# Site settings
title: Joe Phillips
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "joephillips.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joe Phillips
user_description: As a seasoned angel investor, I specialize in identifying and supporting the most promising innovations in the biotech sector. With a keen eye for disruptive technologies and a passion for driving scientific advancements, I leveraged my extensive network and expertise to provide strategic funding and mentorship to early-stage biotech startups.
user_title: Angel Investor
email: joephillips@me.com
twitter_username: 
github_username:  
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
